MCNP6 support
svalinn/DAGMC pull request #460
Opened 2016-11-23 02:04 UTC by ljacobson64

This PR adds DAGMC integration for MCNP6. The bulk of the changes is the addition of the two patch files for versions 6.1 and 6.1.1. Significant changes were also made to mcnp_funcs.cpp to accommodate more types of metadata (MCNP6 particle types, FCL, etc.) in the gcad files.

2016-11-23 02:26 UTC, makeclean requested changes
I think there is a little git work to do to remove the commits that arent part of the mcnp/mcnp6 work. Also the question regarding the if statements.

2016-11-23 02:26 UTC, makeclean commented on common/CMakeLists.txt
> +                           PUBLIC_HEADER DESTINATION ${INSTALL_INCLUDE_DIR})
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 02:26 UTC, makeclean commented on fluka/CMakeLists.txt
> +                       PUBLIC_HEADER DESTINATION ${INSTALL_INCLUDE_DIR})
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 02:26 UTC, makeclean commented on fluka/build/CMakeLists.txt
> +install(TARGETS mainfludag DESTINATION ${INSTALL_BIN_DIR})
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 02:26 UTC, makeclean commented on geant4/CMakeLists.txt
> +                         PUBLIC_HEADER DESTINATION ${INSTALL_INCLUDE_DIR})
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 02:26 UTC, makeclean commented on gtest/CMakeLists.txt
> +                      ARCHIVE       DESTINATION ${INSTALL_LIB_DIR})
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 02:26 UTC, makeclean commented on mcnp/mcnp6/CMakeLists.txt
> +  add_definitions(-DTHREAD="MCNP6")
is the difference between the 6.1 branch of this if statement and the 6.1.1 branch to maintain parity with the LANL version, or should we make these more consistent?

2016-11-23 02:26 UTC, makeclean commented on uwuw/CMakeLists.txt
> -install(TARGETS uwuw_preproc DESTINATION bin)
this seems very unrelated to mcnp6

2016-11-23 02:26 UTC, makeclean commented on tools/make_watertight/CMakeLists.txt
> +install(TARGETS check_watertight make_watertight DESTINATION ${INSTALL_BIN_DIR} PERMISSIONS)
these changes are unrelated to mcnp6, should they be in the pr?

2016-11-23 05:13 UTC, ljacobson64 commented on mcnp/mcnp6/CMakeLists.txt
> +  add_definitions(-DTHREAD="MCNP6")
The differences are to maintain parity with the LANL versions. I copied those variables directly from `mcnp_env.F90`, which is a source file produced by the perl script `mcnp_env.pl`. The values of those variables in the CMakeLists are what appeared in `mcnp_env.F90` for versions 6.1 and 6.1.1.

Upon further investigation, the script `VC_info.gcf` contains `THREAD = MCNP6` and `REL_VERS = 1.0` for 6.1 and `THREAD = MCNP` and `REL_VERS = 6.1.1b` for 6.1.1.

2016-11-23 05:29 UTC, ljacobson64 commented
The extraneous non-MCNP6 commits should be gone now

2016-11-23 14:45 UTC, ljacobson64 commented
I'll preemptively answer the question about why I renamed the patch files: if you end them with `.patch`, you get syntax highlighting on github

2016-12-07 01:44 UTC, makeclean commented
Thanks @ljacobson64, this is great :)

2016-12-07 01:44 UTC, merged