Add some tests and fix others
svalinn/DAGMC pull request #472
Opened 2017-01-09 20:18 UTC by ljacobson64

This PR adds 2 tests to test_TrackLengthMeshTally which make sure tetmeshes work for neutrons and protons. It also fixes some existing dagmcnp tests and adds them to the travis run script.

2017-01-09 21:57 UTC, ljacobson64 commented
Just commenting that the tests are expected to fail for this PR until #470 is merged, at which point the tests should pass

2017-02-14 19:12 UTC, makeclean commented
#470 is now merged, can you rebase and push?

2017-02-14 19:17 UTC, ljacobson64 commented
Done, fingers crossed

2017-02-14 19:32 UTC, ljacobson64 commented
:(

2017-02-14 19:37 UTC, ljacobson64 commented
This is failing because the dagmcnp_unit_tests aren't being built, because we aren't using `-DBUILD_MCNP5` or `-DBUILD_MCNP6`, which we can't use because that would require us to build MCNP. The way around this would be to build the MCNP tests every time regardless of whether MCNP is being built.

2017-02-14 19:49 UTC, makeclean commented
Yeah we should always build those in testing

2017-02-14 19:54 UTC, ljacobson64 commented
Perhaps a `-DBUILD_TESTS` flag which we would only use for the CI

2017-02-14 21:22 UTC, makeclean commented
Good to go?

2017-02-14 21:29 UTC, ljacobson64 commented
Yes

2017-02-14 21:34 UTC, makeclean requested changes

2017-02-14 21:34 UTC, makeclean commented on mcnp/test/CMakeLists.txt
> +include_directories(../../common)
could you change this to ${CMAKE_SOURCE_DIR}/common

2017-02-14 21:34 UTC, makeclean commented on mcnp/test/CMakeLists.txt
> -setup_test(dagmcnp_unit_tests cpp ${DRIVER} "${LINK_LIBS}")
Are you changing this for all the tests? What was the reason for this change?

2017-02-14 21:35 UTC, ljacobson64 commented on mcnp/test/CMakeLists.txt
> -setup_test(dagmcnp_unit_tests cpp ${DRIVER} "${LINK_LIBS}")
mcnp_funcs.cpp needs to be in there for this one, and the setup_test macro doesn't allow for adding additional source files

2017-02-14 21:36 UTC, ljacobson64 commented on mcnp/test/CMakeLists.txt
> -setup_test(dagmcnp_unit_tests cpp ${DRIVER} "${LINK_LIBS}")
To elaborate, mcnp_funcs.cpp needs to be in there when you don't build DAG-MCNP for some reason

2017-02-14 21:43 UTC, ljacobson64 commented on mcnp/test/CMakeLists.txt
> -setup_test(dagmcnp_unit_tests cpp ${DRIVER} "${LINK_LIBS}")
```
CMakeFiles/dagmcnp_unit_tests.dir/dagmcnp_unit_tests.cpp.o: In function `DAGMCNP5Test_dagmcinit_test_Test::TestBody()':
dagmcnp_unit_tests.cpp:(.text+0x1cf): undefined reference to `dagmcwritemcnp_'
dagmcnp_unit_tests.cpp:(.text+0x3a6): undefined reference to `dagmc_teardown_'
```

2017-02-14 23:07 UTC, ljacobson64 commented on mcnp/test/CMakeLists.txt
> +include_directories(../../common)
Whoops, didn't see this one. Fixed now.

2017-02-15 15:22 UTC, makeclean reviewed
Awesome

2017-02-15 15:22 UTC, makeclean approved these changes

2017-02-15 15:23 UTC, merged