Only require fortran compiler if building MCNP5/6
svalinn/DAGMC pull request #701
Opened 2020-09-09 14:05 UTC by pshriwise

## Description
As of #686 we no longer have a strict dependency on a Fortran compiler unless we're building MCNP executables.

## Motivation and Context
For codes requiring only the C++ based libraries we build, this reduces our dependency list.

2020-09-09 15:19 UTC, gonuke requested changes
Thanks @pshriwise - not sure if we need Fortran for Fluka also? @makeclean ?

2020-09-09 15:19 UTC, gonuke commented on CMakeLists.txt
> +if(BUILD_MCNP5 OR BUILD_MCNP6)
Maybe Fluka also?

2020-09-09 15:22 UTC, makeclean commented
No Fortran needed for fluka
________________________________
From: Paul Wilson <notifications@github.com>
Sent: Wednesday, September 9, 2020 4:19:48 PM
To: svalinn/DAGMC <DAGMC@noreply.github.com>
Cc: Davis, Andrew <andrew.davis@ukaea.uk>; Mention <mention@noreply.github.com>
Subject: Re: [svalinn/DAGMC] Only require fortran compiler if building MCNP5/6 (#701)


@gonuke requested changes on this pull request.

Thanks @pshriwise<https://github.com/pshriwise> - not sure if we need Fortran for Fluka also? @makeclean<https://github.com/makeclean> ?

________________________________

In CMakeLists.txt<https://github.com/svalinn/DAGMC/pull/701#discussion_r485696065>:

> @@ -16,6 +16,11 @@ dagmc_setup_build()

 dagmc_setup_options()

+if(BUILD_MCNP5 OR BUILD_MCNP6)


Maybe Fluka also?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/svalinn/DAGMC/pull/701#pullrequestreview-485120947>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASTUSQIN3YGL3ORLAG6ABDSE6MJJANCNFSM4RCK7UPQ>.

2020-09-09 15:58 UTC, bam241 approved these changes
LGTM !

2020-09-09 16:02 UTC, pshriwise commented
Testing this with an MCNP build to make sure it isn't breaking that... will confirm one way or the other shortly.

2020-09-09 17:24 UTC, pshriwise commented
Successfully built DAG-MCNP6 and tests passed. :heavy_check_mark:

2020-09-10 13:09 UTC, gonuke approved these changes

2020-09-10 13:09 UTC, gonuke commented
Thanks @pshriwise

2020-09-10 13:09 UTC, merged

2020-09-10 21:25 UTC, Shimwell commented
This is great, just perfect for OpenMC

Would we also need another release to target this in a conda recipe