Add BUILD_EXE as cmake option
svalinn/DAGMC pull request #717
Opened 2020-12-21 16:51 UTC by bam241

This should allow to build dagmc libs (shared and.or static) without the exe.

2020-12-21 16:57 UTC, ljacobson64 commented on cmake/DAGMC_macros.cmake
> +  if (NOT BUILD_EXEC)
This should be `BUILD_EXE` not `BUILD_EXEC`

2020-12-21 17:00 UTC, bam241 commented
I am now missing the includes :( in the install folder....

2020-12-21 17:05 UTC, ljacobson64 commented
I think that's a problem in the `dagmc_install_library` macro, not something you did. The shared library section starts like this:

```
  if (BUILD_SHARED_LIBS)
    add_library(${lib_name}-shared SHARED ${SRC_FILES})
      set_target_properties(${lib_name}-shared
        PROPERTIES OUTPUT_NAME ${lib_name}
        PUBLIC_HEADER "${PUB_HEADERS}")
```

while the static library section starts like this:

```
  if (BUILD_STATIC_LIBS)
    add_library(${lib_name}-static STATIC ${SRC_FILES})
    set_target_properties(${lib_name}-static
      PROPERTIES OUTPUT_NAME ${lib_name})
```

The static library section doesn't set the public headers as part of the target properties.

2020-12-21 18:21 UTC, bam241 commented
included the static header install fix in this PR....

2020-12-24 22:49 UTC, pshriwise requested changes
Just a few small items from me here.

2020-12-24 22:49 UTC, pshriwise commented on cmake/DAGMC_macros.cmake
> +  option(BUILD_EXE "Build DAGMC executables" ON)
Let's indent the comment string to match the other options.

2020-12-24 22:49 UTC, pshriwise commented on cmake/DAGMC_macros.cmake
> +    message("Turning BUILD_EXE to OFF: SHARED_BUIL_LIBS and BUILD_STATIC_EXE are OFF")
```suggestion
    message("Turning BUILD_EXE OFF: SHARED_BUILD_LIBS and BUILD_STATIC_EXE are OFF")
```

2020-12-24 22:49 UTC, pshriwise commented on news/PR-0717.rst
> +- now install dagmc header when building and instaling static libs
Some formatting updates so the news file renders correctly.
```suggestion
**Added:**

- adding BUILD_EXE option (default ON) alowing to build only the dagmc libs
  without the executable (for static and/or shared libs)

**Changed:** None

- now install dagmc header when building and instaling static libs

```

2020-12-24 22:49 UTC, pshriwise commented on cmake/DAGMC_macros.cmake
> +    message("Turning BUILD_EXE to OFF: SHARED_BUIL_LIBS and BUILD_STATIC_EXE are OFF")
I'll suggest we make this a warning message so it's more noticeable.

2021-01-20 23:30 UTC, bam241 commented
@pshriwise is there some still some undressed comment in here ?

2021-01-21 17:14 UTC, ljacobson64 commented
@bam241 can you remind me what the use case is for building without executables?

2021-01-21 17:33 UTC, bam241 commented
> @bam241 can you remind me what the use case is for building without executables?

The plugin.

2021-02-04 03:08 UTC, pshriwise approved these changes
All my comments were addressed. Looks good @bam241!

2021-02-15 12:51 UTC, gonuke approved these changes
LGTM - thanks @bam241

2021-02-15 12:51 UTC, merged