updating locating to downlod the plugin
svalinn/DAGMC pull request #744
Opened 2021-06-22 19:09 UTC by bam241

using the news release location to download the plugin

2021-06-22 19:29 UTC, gonuke requested changes
I wonder if we should revise our mention of the "DAGMC Plugin" to be the "Cubit Plugin" or the "Svalinn Plugin for Cubit"? or something???

2021-06-22 19:29 UTC, gonuke commented on doc/install/plugin.rst
> +..  _DAGMC_plugins: https://github.com/svalinn/Cubit-plugin/releases/tag/0.1.0
Maybe we should just reference the release page `https://github.com/svalinn/Cubit-plugin/releases` without a specific release, which will allow this to be generic across future releases.

2021-06-24 14:45 UTC, bam241 commented
@gonuke I applied the suggested change, anything else ?

2021-06-24 15:38 UTC, gonuke commented
I had a general recommendation to change how we refer to the plug-in, but maybe this is a different issue.

For DAGMC people, it is a Cubit plugin.  For Cubit people, it is a DAGMC plugin.  Since it includes mcnp2cad, it is actually a Svalinn plugin(?)....

2021-06-30 14:30 UTC, gonuke approved these changes

2021-06-30 14:30 UTC, gonuke commented
Thanks @bam241 - we'll tackle the generic naming convention in the future

2021-06-30 14:30 UTC, merged

2021-06-30 14:31 UTC, gonuke commented
Now someone needs to rebuild the website?