moved to sequential docker building
svalinn/DAGMC pull request #748
Opened 2021-07-08 08:58 UTC by Shimwell

## Description
This is a minor change to the docker CI image building process. It uses "needs" keyword in the steps for docker images building to ensure the images are getting the most up to date version of the previous image.

This has a nice upgrade path as I think it is compatible with docker layer caching which would speed up the overall process.

Also if we like a badge can be added to the README ?
[![.github/workflows/docker_publish.yml](https://github.com/svalinn/DAGMC/actions/workflows/docker_publish.yml/badge.svg)](https://github.com/svalinn/DAGMC/actions/workflows/docker_publish.yml)

## Motivation and Context
Ensures images build on the latest previous base images
Cleaner presentation of build process with connections between images identified

## Changes
What kind of change does this PR introduce? (Bug fix, feature, documentation update...)
update to current GH action building the dockerfiles

## Behavior
What is the current behavior? What is the new behavior?
Current behavior is one large matrix of builds, new process is sequential matrixes of builds with "needs" keyword 

## Other Information
Other relevant information to this pull request.

## News file
All pull requests are required to include an updated news file with the PR.
The file should be located at the `/news/PR-<#>.rst` where `<#>` should be replaced with the appropriate PR number.
Please see [here](https://github.com/svalinn/DAGMC/blob/develop/news/TEMPLATE.rst) for the news file template.

2021-07-08 12:57 UTC, gonuke requested changes
Thanks @Shimwell - just one small optional change

2021-07-08 12:57 UTC, gonuke commented on .github/workflows/docker_publish.yml
> +          16.04,
We only need to build the housekeeping image on one of these

2021-07-08 12:58 UTC, gonuke commented
Perhaps add the badge to the README as part of this PR, as well?

Why is this failing on circleci?

2021-07-08 14:11 UTC, Shimwell commented on .github/workflows/docker_publish.yml
> +          18.04,
```suggestion
```

2021-07-08 14:17 UTC, Shimwell commented
I've added the badge to the readme and removed the unnecessary housekeeping build with Ubuntu 18.04

2021-07-08 14:38 UTC, gonuke commented
Can you rebase this? it should allow it to pass the CircleCI builds as well

2021-07-08 15:06 UTC, bam241 commented
I manually restarted the CI to make sure we have correctly identified (and fix) the issue with CI here.

2021-07-08 15:17 UTC, gonuke commented
still failing on circle because it doesn't have the right Pyhton 3 stuff maybe?

2021-07-08 15:17 UTC, gonuke commented
that's why it may need the rebase?

2021-07-08 17:51 UTC, gonuke approved these changes

2021-07-08 17:53 UTC, gonuke commented
I'm a little confused that the changes from #747 are showing up as changes here.... it probably doesn't matter...

2021-07-09 13:47 UTC, gonuke commented
I rebased again to cleanup the history

2021-07-09 13:48 UTC, gonuke commented
Will merge after tests pass - they should since the code is identical to the last set of tests!

2021-07-14 22:14 UTC, bam241 commented
looking good merging.

(so we see if we can still push imp to svalinn  registry)

2021-07-14 22:14 UTC, merged