integration of test for dockerfile update
svalinn/DAGMC pull request #754
Opened 2021-07-12 16:00 UTC by bam241

duplicating test for docker file update.

2021-07-12 16:04 UTC, bam241 commented
also added a contiditon push based on PR status

2021-07-12 16:04 UTC, bam241 commented
@Shimwell do you know if my implementation will use cashed img ?

2021-07-12 16:43 UTC, Shimwell commented
> @Shimwell do you know if my implementation will use cashed img ?

I can see 12 jobs all running in parallel as the first stage. I don't think these will make use of cached images.

Perhaps the ```needs``` argument can be used in a few places to make sure the base images have been built first

2021-07-12 18:55 UTC, gonuke requested changes

2021-07-12 18:55 UTC, gonuke commented on .github/workflows/docker_publish.yml
> +          tags: ghcr.io/svalinn/test_dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}
This will need to include some other unique string (sha?) to avoid two simultaneous PR's from overwriting each other

2021-07-12 19:29 UTC, gonuke commented on .github/workflows/docker_publish.yml
> +          if [ "${{ matrix.isMerged }}" == "true" ]; then
Maybe I don't understand how the `isMerged` works, but this seems like the logic is reversed.  Don't we want the sha for PRs and without a sha for merged?

2021-07-14 19:22 UTC, gonuke requested changes
Oops

2021-07-14 19:22 UTC, gonuke commented on CI/Dockerfile_1_external_deps
> +ROOT_NAME=dagmc
```suggestion
ARG ROOT_NAME=dagmc
```

2021-07-15 15:34 UTC, bam241 commented
closing and reopening from upstream

2021-07-16 17:56 UTC, bam241 commented
this is actually looking at my run on push, not the one on PR... very strange !

2021-07-16 18:04 UTC, bam241 commented
here is the place where the test gets run on my user name: https://github.com/bam241/DAGMC/actions/workflows/docker_publish.yml

2021-07-17 11:32 UTC, gonuke requested changes
This should fix the most recent error

2021-07-17 11:32 UTC, gonuke commented on CI/Dockerfile_3_moab
> +AARG OWNER=svalinn
```suggestion
ARG OWNER=svalinn
```

2021-07-17 17:28 UTC, bam241 commented
@gonuke thx for the suggestion ! it seems tone working now !


One need to make sure the retagging is working well, then I disable retag on personal branch and this should be good to go.

2021-07-17 17:29 UTC, bam241 commented
not that I rearranged @Shimwell slicing to avoid uploading image we don't use or don't need to exchange between jobs...

2021-07-18 05:16 UTC, gonuke requested changes
Another typo?

2021-07-18 05:16 UTC, gonuke commented on .github/workflows/docker_publish.yml
> +          /bin/bash "/scripts/tests.sh"
This is the wrong path.... maybe
```suggestion
          /bin/bash "CI/scripts/tests.sh"
```

2021-07-18 20:50 UTC, gonuke commented
If we hard-coded the matrix, could we get more parallelism on the expensive builds?

2021-07-18 21:26 UTC, bam241 commented
@gonuke I am happy with his.

package are tagged as stable when test pass (set on merge) https://github.com/bam241/DAGMC/pkgs/container/dagmc-ci-ubuntu-18.04-gcc-ext-hdf5_1.10.4-moab_develop

I also limited the retagging to svalinn only to limit the amount of pollution we are producing in users forks....

2021-07-18 21:28 UTC, gonuke approved these changes

2021-07-18 21:28 UTC, bam241 commented
> If we hard-coded the matrix, could we get more parallelism on the expensive builds?

we already have parallelism for the 4 expensive builds

2021-07-18 21:30 UTC, bam241 commented
see https://github.com/bam241/DAGMC/actions/runs/1042760146 
the `Matrix: build-deps-img` box

2021-07-18 21:30 UTC, gonuke commented
> > If we hard-coded the matrix, could we get more parallelism on the expensive builds?
> 
> we already have parallelism for the 4 expensive builds

OK! I must have been looking at something old that looked slower.

2021-07-18 21:31 UTC, gonuke commented
I'll wait for CircleCI (should be OK) and then merge

2021-07-18 21:41 UTC, gonuke commented
Thanks for tackling this @bam241

2021-07-18 21:41 UTC, merged