Direct bounding box calls to relevant methods when using Double-Down
svalinn/DAGMC pull request #779
Opened 2021-08-16 14:23 UTC by pshriwise

@Shimwell noted that bounding boxes coming out of DAGMC when using Double-Down aren't correct. I thought I had included wrappers for the relevant methods in DAGMC, but it appears that slipped through the cracks. This updates our `getobb` calls to the correct methods on the `ray_tracer` object in Double-Down. Unfortunately, this means a couple more `#ifdef`'s for now as that method relies on the `RayTracingInterface` in Double-Down rather than the `GeomTopoTool`.

2021-08-16 14:39 UTC, pshriwise commented
Realizing that we could've caught this earlier with a bounding box check, so I added one to the `dagmc_simple_test`. I confirmed that it fails before https://github.com/svalinn/DAGMC/pull/779/commits/c82c164d9c175a961470b3f3d11593f96d430c7f and passes after with Double-Down enabled.

2021-08-16 15:01 UTC, shimwell commented
Thanks @pshriwise much appreciated. I can check this out and report back

2021-08-16 20:04 UTC, Shimwell commented
I've run the openmc bounding box task that was previously failing and it now works, nice work @pshriwise

2021-08-17 10:49 UTC, gonuke requested changes
Thanks @pshriwise - feels almost petty to point out this inconsequential typo in a comment...

2021-08-17 10:49 UTC, gonuke commented on src/dagmc/DagMC.cpp
> +/* SECTION IV: : Handling DagMC settings */
```suggestion
/* SECTION IV: Handling DagMC settings */
```

2021-08-17 10:55 UTC, gonuke commented
We can remove the `#ifdef` in the future with a `get_obb()` method in GQT that just wraps its GTT method of the same name, right?

2021-08-17 12:02 UTC, pshriwise commented on src/dagmc/DagMC.cpp
> +/* SECTION IV: : Handling DagMC settings */
Haha thanks for catching it!

2021-08-17 12:04 UTC, pshriwise commented
> We can remove the `#ifdef` in the future with a `get_obb()` method in GQT that just wraps its GTT method of the same name, right?

Yep, that should be totally possible. I've thought about merging those two classes (perhaps in DAGMC to start) so we have a single object for the ray tracing and geometry, but I haven't had time to take a crack at it.

2021-08-17 14:18 UTC, gonuke approved these changes

2021-08-17 14:19 UTC, merged