Mac ci
svalinn/DAGMC pull request #780
Opened 2021-08-20 05:37 UTC by bam241

first attempt to setup MACOS CI

2021-08-21 15:56 UTC, gonuke commented
Maybe start with the build strategy in the condo-forge Moab-feedstock? (Just a thought)

2021-08-22 13:39 UTC, gonuke requested changes
Thanks for sorting this out @bam241 - a little change for consitency

2021-08-22 13:39 UTC, gonuke commented on .github/workflows/mac_build_test.yml
> +  main:
```suggestion
  BuildTest:
```

2021-08-22 16:32 UTC, gonuke commented
Thanks for the quick work here @bam241. I'm merging this first because the rebase will probably be simpler this way around

2021-08-22 16:33 UTC, merged

2021-08-22 21:35 UTC, pshriwise commented
Thanks for tracking down the cause of the problem here @bam241!