Geant4 v11 update
svalinn/DAGMC pull request #924
Opened 2023-11-30 23:28 UTC by gonuke

Note: These changes were first proposed in #907 by @ahnaf-tahmid-chowdhury.  In order for the docker build process to test smoothly, a new PR is being issued with all those changes, attributed to him, but without updating the standard `linux_build_test.yml` workflow. That workflow will require the new docker images to exist first.

## Description
Introduce changes to support building against Geant4 v11.x

## Motivation and Context
Some code API changes for Geant4 require some changes.

## Changes
Supports build of newer versions of Geant4

2023-11-30 23:30 UTC, gonuke commented
Mac testing will fail until we merge #922

2023-12-01 01:16 UTC, ahnaf-tahmid-chowdhury commented
I think, there is no need to install gcc manually. GitHub workflow already comes with built-in dev tools.

2023-12-01 03:27 UTC, gonuke commented
I'm trying to skip gcc in #922 right now

2023-12-01 15:09 UTC, gonuke commented
> I think, there is no need to install gcc manually. GitHub workflow already comes with built-in dev tools.

Thanks @ahnaf-tahmid-chowdhury - I've moved that change into this PR since it was such a small change.

Looking for a review here from @pshriwise @shimwell @makeclean @helen-brooks ?

2023-12-06 20:26 UTC, pshriwise requested changes
Thanks @ahnaf-tahmid-chowdhury and @gonuke for the update to a newer Geant4 version.

Mostly line comments on the Python script here.

2023-12-06 20:26 UTC, pshriwise commented on .github/workflows/mac_build_test.yml
> +          brew install eigen hdf5
I didn't see `gcc@6` removed in the original PR. Can I ask why it was removed here?

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +                print("Error: can't find DAG file")
```suggestion
                print("Error: can't find DAG file: '{}' ".format(options.dag_file))
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +        print("Assuming all volumes contain vacuum")
```suggestion
        print("There are no materials in the h5m file.\n "
                "Assuming all volumes contain vacuum")
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +        print("dag volume names not assigned", sys.exc_info()[0])
```suggestion
        print("DAGMC volume names are not assigned", sys.exc_info()[0])
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +                print("Error: "+key+" file exists")
```suggestion
                print("Error: {} file exists".format(key))
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +        print("Error: can't create directory, "+path)
```suggestion
        print("Error: can't create directory '{}' ".format(path))
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +    dag_vol_names = [dag_materials.keys()]
```suggestion
    dag_vol_names = list(dag_materials.keys())
```

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +                print("Error: can't find DAG file")
To avoid the extra `else` block at the end:

```python
try:
    fh = open(options.dag_file, 'r')
    fh.close()
except IOError:
    print("Error: can't find DAG file: '{}'".format(options.dag_file))

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/generate_geant4
> +"""
Any reason not to remove this function?

2023-12-06 20:26 UTC, pshriwise commented on src/geant4/app/src/ExN01UserScoreWriter.cc
> +// retrieve the map
These lines are also just above. We should only need this once. Might be a change inherited from the original PR.

2023-12-06 22:42 UTC, gonuke commented on .github/workflows/mac_build_test.yml
> +          brew install eigen hdf5
I had a standalone PR for this line only, because it's causing MacOS builds to fail.  Since it was a single line, I moved it here rather than waiting for that PR to be reviewed separately (given the difficulty getting reviews here)

2023-12-07 02:48 UTC, gonuke commented
Thanks for the review @pshriwise - I think I addressed everything.

2023-12-07 03:26 UTC, pshriwise approved these changes
Thanks @gonuke!

2023-12-07 03:26 UTC, merged