Update build instructions for DAGMC dependencies
svalinn/DAGMC pull request #963
Opened 2024-10-25 18:25 UTC by gonuke

The instructions for building DAGMC were extremely out of date.

This updates them, and we will try to publish new ones.

2024-10-26 06:01 UTC, ahnaf-tahmid-chowdhury requested changes
Thanks for the update. 

Instructions for installing hdf5 in RPM based distro would be:

```sh
sudo yum install -y epel-release
sudo yum config-manager --enable epel
sudo yum install hdf5-devel
```

If Eigen3 is a dependency of DAGMC, we should either create a method to enable it from the DAGMC side or ask users to enable it in MOAB, as MOAB has made Eigen3 an optional dependency. However, MOAB 5.5.1 is good to go.

2024-10-26 06:01 UTC, ahnaf-tahmid-chowdhury commented on doc/install/dependencies.rst
> +..  _MOAB: http://bitbucket.org/fathomteam/moab
```suggestion
..  _MOAB: https://sigma.mcs.anl.gov/moab-library/
```

2024-10-26 06:01 UTC, ahnaf-tahmid-chowdhury commented on doc/CHANGELOG.rst
> +  * Updated documentation to build dependencies ()
```suggestion
  * Updated documentation to build dependencies (#963)
```

2024-11-14 20:27 UTC, gonuke commented
I think this is ready to merge now @ahnaf-tahmid-chowdhury - after which I'll publish the release

2024-11-15 12:26 UTC, ahnaf-tahmid-chowdhury approved these changes
Thank you.

2024-11-15 12:27 UTC, merged